#if !canImport(ObjectiveC)
import XCTest

extension Argon2SwiftTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Argon2SwiftTests = [
        ("testArgon2d", testArgon2d),
        ("testArgon2i", testArgon2i),
        ("testArgon2id", testArgon2id),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(Argon2SwiftTests.__allTests__Argon2SwiftTests),
    ]
}
#endif
